name: newsfeed
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.1.0+1
  webfeed: ^0.4.2
  http: ^0.12.0+2
  cloud_firestore: ^0.13.5
  uuid: ^2.0.4
  url_launcher: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true